apparently 1e-4 tolerance isn't met either (J8 fail). this failure is only good to 1e-3. changing tolerance to 1e-3 Caused by: java.lang.RuntimeException: java.lang.AssertionError: expected:<2.5813652> but was:<2.581196819615877>     at hex.pca.PCATest.testArrestsScoring(PCATest.java:183)     ... 35 more Caused by: java.lang.AssertionError: expected:<2.5813652> but was:<2.581196819615877>     at org.junit.Assert.fail(Assert.java:88)     at org.junit.Assert.failNotEquals(Assert.java:743)     at org.junit.Assert.assertEquals(Assert.java:494)     at org.junit.Assert.assertEquals(Assert.java:592)     at hex.pca.PCATest.checkStddev(PCATest.java:25)     at hex.pca.PCATest.testArrestsScoring(PCATest.java:175)