moved large pyunit to NOPASS due to failing intermittently with:
03-12 09:07:20.290 172.16.2.173:56795    27660  FJ-0-3    INFO: GLM2[dest=GLMModel__b3280f0a7fdced8fbca7ab471004370, iteration=109, lambda = 0.07966564745559518]: invoking line search
barrier onExCompletion for hex.glm.GLM$1@399dfb72
java.lang.AssertionError: unexpected pending count, expected 1, got 2
	at hex.glm.GLM$GLMLambdaTask$LineSearchIteration.callback(GLM.java:672)
	at hex.glm.GLM$GLMLambdaTask$LineSearchIteration.callback(GLM.java:667)
	at water.H2O$H2OCallback.onCompletion(H2O.java:666)
	at jsr166y.CountedCompleter.tryComplete(CountedCompleter.java:386)
	at water.MRTask.compute2(MRTask.java:439)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:608)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:429)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

on:
data: smalldata/arcene/shuffle_test_version/arcene_shuffled.csv
h2o.glm(x=train_data_shuffled[0:1000], y=train_data_shuffled[1000], family="binomial", lambda_search=True, alpha=[0.5], n_folds=0, use_all_factor_levels=True)